---
# Copyright 2022, BBC R&D.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Include tasks for EL
  ansible.builtin.include_tasks:
    file: glusterfs_install_dnf.yml
  when: ansible_facts['pkg_mgr'] == 'dnf'

- name: Install glusterfs server packages
  ansible.builtin.package:
    name: "{{ glusterfs_server_distro_packages }}"
    state: "{{ glusterfs_package_state }}"

- name: Drop glusterfs-wait.sh script
  ansible.builtin.copy:
    src: glusterfs-wait.sh
    dest: /usr/local/sbin
    mode: "0744"

- name: Add glusterd.service overrides
  ansible.builtin.import_role:
    name: systemd_service
  vars:
    systemd_services:
      - service_name: glusterd
        systemd_overrides_only: true
        systemd_overrides:
          Service:
            ExecStartPost: "/usr/local/sbin/glusterfs-wait.sh"

- name: Configure systemd-tmpfiles to create /dev/fuse at boot
  ansible.builtin.copy:
    content: "c /dev/fuse 0600 - - - 10:229"
    dest: "/etc/tmpfiles.d/openstack-ansible-glusterfs-server.conf"
    mode: "0644"
  when: not (is_metal | default(False)) | bool
  register: _glusterfs_server_tmpfiles

- name: Restart systemd-tmpfiles-setup-dev
  ansible.builtin.service:
    name: "systemd-tmpfiles-setup-dev"
    enabled: true
    state: restarted
  when:
    - not (is_metal | default(False)) | bool
    - _glusterfs_server_tmpfiles is changed

- name: Start glusterfs server
  ansible.builtin.service:
    name: "{{ glusterfs_server_service }}"
    enabled: true
    state: started
